const { Dog } = require('../models/dog');

const dogData = [
  {
    dog_name: 'Aspen',
    gender: 'male',
    breed: 'labrador retriever',
    age: 1,
    size: 'large',
    user_id: 1,
    note: 'vaccines up to date',
  },
  {
    dog_name: 'Athena',
    gender: 'female',
    breed: 'bulldog',
    age: 4,
    size: 'large',
    user_id: 2,
    note: 'Allergic to peanuts',
  },
  {
    dog_name: 'Bailey',
    gender: 'male',
    breed: 'german shepherd',
    age: 2,
    size: 'extra-large',
    user_id: 3,
    note: 'allergic to fish',
  },
  {
    dog_name: 'Coco',
    gender: 'female',
    breed: 'poodle',
    age: 3,
    size: 'small',
    user_id: 4,
    note: 'Allergic to peanuts',
  },
  {
    dog_name: 'Daisy',
    gender: 'female',
    breed: 'golden retriever',
    age: 1,
    size: 'large',
    user_id: 5,
    note: 'No allergies',
  },
  {
    dog_name: 'Bear',
    gender: 'male',
    breed: 'chihuahua',
    age: 2,
    size: 'small',
    user_id: 6,
    note: 'Afraid of lightning and thunders. Special diet.',
  },
  {
    dog_name: 'Edie',
    gender: 'male',
    breed: 'french bulldog',
    age: 2,
    size: 'medium',
    user_id: 7,
    note: 'Rescued with history of neglecting.',
  },
  {
    dog_name: 'Greta',
    gender: 'female',
    breed: 'afghan hound',
    age: 5,
    size: 'large',
    user_id: 8,
    note: 'pending proof of vaccination status',
  },
  {
    dog_name: 'Izzy',
    gender: 'female',
    breed: 'great Dane',
    age: 1,
    size: 'extra-large',
    user_id: 9,
    note: 'pending proof of vaccination status',
  },
  {
    dog_name: 'Kona',
    gender: 'male',
    breed: 'terrier',
    age: 2,
    size: 'medium',
    user_id: 10,
    note: 'presenting separation anxiety behaviors since last week',
  },
  {
    dog_name: 'Lola',
    gender: 'female',
    breed: 'siberian husky',
    age: 3,
    size: 'large',
    user_id: 11,
    note: 'afraid of motorcycles. allergic to wheat',
  },
  {
    dog_name: 'Basil',
    gender: 'male',
    breed: 'pug',
    age: 2,
    size: 'small',
    user_id: 12,
    note: 'Basil is booked to stay for two weeks in August 2022. Pending dates confirmation',
  },
];

const seedDog = () => Dog.bulkCreate(dogData);

module.exports = seedDog;
